language: csharp
mono: none
solution: EfYouCore\EfYouCore.sln
dotnet: 3.1

before_script: 
- dotnet restore ".\EfYouCore\EfYouCore.sln" 

script: 
- dotnet build ".\EfYouCore\EfYouCore.sln" -c Release 
- dotnet test ".\EfYouCore\EfYouCore.sln" -c Release -v n