language: csharp
mono: none
solution: EfYou.sln
dotnet: 3.1

before_script: 
- dotnet restore ".\EfYou.sln" 

script: 
- dotnet build ".\EfYou.sln" -c Release 
- dotnet test ".\EfYou.sln" -c Release -v n /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
- npm run coveralls